#  db
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}   # least-privilege DB role, only has access to admin schema
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA}  # all JPA queries/DDL go to THE schema
  flyway:
    schemas:  ${DB_SCHEMA}              # Flyway creates/owns this schema
    default-schema:  ${DB_SCHEMA}       # flyway_schema_history also lives here
    locations:
      - classpath:db/migration
      - classpath:db/shared-migration
server:
  port: 8080